/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package controlador;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import modelo.Aeropuerto;
import modelo.Hora;
import modelo.Itiner;
import modelo.Pasajero;

/**
 *
 * @author Galvez
 */
public class ComprarBoleto extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroAvion
     */
    ArrayList<Pasajero> pasajeros;
    ArrayList<String> destinos;
    ArrayList<Pasajero> pasajerosConBoleto;
    Aeropuerto aeropuerto;
    boolean disponibilidad=false;
    private Menu padre;
    
    public ComprarBoleto(Menu padre) {
        this.padre=padre;
        initComponents();
        pasajeros=padre.getPais().getPasajerosSegun(padre.getId());
        destinos=padre.getPais().getNombresDestinosPara(padre.getId());
        aeropuerto=padre.getPais().getAeropuertoSegun(padre.getId());
        pasajerosConBoleto=padre.getPais().getPasajerosConBoletoSegun(padre.getId());
        //disponibles=padre.getPais().getDisponiblesSegun(padre.getId()-1);
        for(int i=0;i<pasajeros.size();i++){
            cbPasajeros.addItem(pasajeros.get(i).getNombre()+"-"+pasajeros.get(i).getCI());
        }
        text1.setText(padre.getNam());
        for(int j=0; j<destinos.size();j++){
            cbDestino.addItem(destinos.get(j));
        }
        if(aeropuerto.tieneAsientosDisponibles()){   
            lblMensaje.setText("Existe disponibilidad de asientos");
            disponibilidad=true;
        }else{    
            lblMensaje.setText("No existe disponibilidad de asientos");
            disponibilidad=false;
        }
        //webfecha.setText( new Date ().getDay()+"."+new Date ().getMonth()+"."+new Date ().getYear() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        tex2 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDestino = new javax.swing.JComboBox();
        llbl0 = new javax.swing.JLabel();
        cbPasajeros = new javax.swing.JComboBox();
        text1 = new javax.swing.JTextField();
        cbClase = new javax.swing.JComboBox();
        lblMensaje = new javax.swing.JLabel();
        cajaFecha = new javax.swing.JTextField();
        cajaHora = new javax.swing.JTextField();

        setTitle("Comprar Boleto");

        lbl2.setText("Origen");

        lbl3.setText("Destino");

        tex2.setText("20");

        lbl4.setText("Costo [$]");

        lbl1.setText("Fecha");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora");

        jLabel2.setText("clase");

        cbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinoActionPerformed(evt);
            }
        });

        llbl0.setText("Pasajero");

        cbPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPasajerosActionPerformed(evt);
            }
        });

        text1.setEditable(false);

        cbClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Turista", "Bussines" }));
        cbClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClaseActionPerformed(evt);
            }
        });

        cajaFecha.setEditable(false);

        cajaHora.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(llbl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbPasajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tex2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbClase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llbl0)
                    .addComponent(cbPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl1)
                    .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cajaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(tex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        padre.setVisibleBoleto();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try {
            if(disponibilidad){
                //String valor=cajaHora.getText();
                Hora hora= new Hora(cajaHora.getText());
                //System.out.println(hora.getHoraString());
                double costo=Double.parseDouble(tex2.getText());
                String clase=cbClase.getSelectedItem().toString();
                String fecha=cajaFecha.getText().replace('.', '/');
                //.getText().replace('.', '/');
                String destino=cbDestino.getSelectedItem().toString();
                String pasajero[]=cbPasajeros.getSelectedItem().toString().split("-");
                
                if(!fecha.equals("")){
                    if(padre.getPais().comprarBoleto(padre.getId(),pasajero[0],Integer.parseInt(pasajero[1])
                    ,fecha ,text1.getText(), destino,clase,costo, hora)){
                        padre.getPanel().actualizarBoleto();
                        padre.getPanel().actualizarTabla();
                    }else
                        JOptionPane.showMessageDialog(null, "Ya no se tiene aviones\ncon destino de "+destino);
                }else JOptionPane.showMessageDialog(null, "Fecha invalida");
            }else JOptionPane.showMessageDialog(null, "No existe Disponibilidad de asientos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
        }
        this.dispose();
        padre.setVisibleBoleto();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cbClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClaseActionPerformed
        // TODO add your handling code here:
        int valor=cbClase.getSelectedIndex();
        if(valor==0)    tex2.setText("20");
        else if(valor==1)    tex2.setText("35.5");
        else if(valor==2)    tex2.setText("50");
    }//GEN-LAST:event_cbClaseActionPerformed

    private void cbPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPasajerosActionPerformed
        // TODO add your handling code here:
        //lblMensaje.setText("Asignado al avion con placa: "+aeropuerto.asignadoA());
    }//GEN-LAST:event_cbPasajerosActionPerformed

    private void cbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinoActionPerformed
        // TODO add your handling code here:
        Itiner it= padre.getPais().getItiner();
        for (int i = 0; i < it.getSize(); i++) {
            if(it.getDatos().get(i).getOrigen().equals(padre.getNam())&&
                    it.getDatos().get(i).getDestino().equals(cbDestino.getSelectedItem().toString())){
                cajaFecha.setText(it.getDatos().get(i).getFecha());
                cajaHora.setText(it.getDatos().get(i).getHora());
            }
        }
    }//GEN-LAST:event_cbDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField cajaFecha;
    private javax.swing.JTextField cajaHora;
    private javax.swing.JComboBox cbClase;
    private javax.swing.JComboBox cbDestino;
    private javax.swing.JComboBox cbPasajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel llbl0;
    private javax.swing.JTextField tex2;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
