/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

import javax.swing.table.DefaultTableModel;
import modelo.Pais;

/**
 *
 * @author Ariel
 */
public class Itinerario extends javax.swing.JFrame {

    /**
     * Creates new form Itinerario
     */
    DefaultTableModel modelo;
    Pais pais;
    public Itinerario(Pais pais) {
        this.pais=pais;
        initComponents();
        actualizarTabla();
    }
    public void actualizarTabla(){
        String cabecera[]={"Origen", "Destino", "Fecha", "Hora"};
        String datos[][]={};
        modelo = new DefaultTableModel(datos, cabecera);
        table.setModel(modelo);
        /*int anchos [] = {120,100,100};
        for(int i=0; i<9; i++){
        	table.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }*/
        for(int i=0;i<pais.getItiner().getSize();i++){
                modelo.addRow(pais.getItiner().getDatos().get(i).getForTable());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Itinerario");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origen", "Destino", "Fecha", "Hora"
            }
        ));
        scpane.setViewportView(table);

        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Seleccione una fila, realize cambios y luego guarde");

        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpane, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMensaje)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpane, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\
        try {
            String fecha=modelo.getValueAt(table.getSelectedRow(), 2).toString();
            String hora=modelo.getValueAt(table.getSelectedRow(), 3).toString();
            pais.getItiner().setDato(table.getSelectedRow(), fecha, hora);
        //System.out.println("fecha: "+fecha+" hora: "+hora);
        } catch (Exception e) {
            lblMensaje.setText("No seleciono ninguna fila de la tabla");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JScrollPane scpane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
