/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package controlador;

import controlador.ComprarBoleto;
import javax.swing.JOptionPane;
import modelo.Pais;
import vista.PanelDibujo;

/**
 *
 * @author Galvez
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registro
     */
    String name;
    RegistroPasajero registroPasajero;
    ComprarBoleto comprarBoleto;
    RegistroAvion registroAvion;
    private PanelDibujo panelDibujo;
    private int id;
    public int getId(){return id;}
    public String getNam(){return name;}
    public PanelDibujo getPanel(){return panelDibujo;}
    public Menu(int id,String nomCorto,PanelDibujo panelDibujo) {
        this.id=id;
        this.name=nomCorto;
        this.panelDibujo=panelDibujo;
        initComponents();
    }
    
    public Pais getPais(){return panelDibujo.getPais();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel(name);
        btnPasajero = new javax.swing.JButton();
        btnBoletos = new javax.swing.JButton();
        btnAvion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Menu");
        setName("menu"); // NOI18N

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setMaximumSize(new java.awt.Dimension(121, 14));
        nombre.setMinimumSize(new java.awt.Dimension(121, 14));
        nombre.setPreferredSize(new java.awt.Dimension(121, 14));

        btnPasajero.setText("Registrar Pasajero");
        btnPasajero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroActionPerformed(evt);
            }
        });

        btnBoletos.setText("Comprar Boleto");
        btnBoletos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBoletos.setMaximumSize(new java.awt.Dimension(121, 23));
        btnBoletos.setMinimumSize(new java.awt.Dimension(121, 23));
        btnBoletos.setPreferredSize(new java.awt.Dimension(121, 23));
        btnBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletosActionPerformed(evt);
            }
        });

        btnAvion.setText("Registrar Avion");
        btnAvion.setBorderPainted(false);
        btnAvion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAvion.setMaximumSize(new java.awt.Dimension(121, 23));
        btnAvion.setMinimumSize(new java.awt.Dimension(121, 23));
        btnAvion.setPreferredSize(new java.awt.Dimension(121, 23));
        btnAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvionActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPasajero, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(btnAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroActionPerformed
        // TODO add your handling code here:
        registroPasajero= new RegistroPasajero(this);
        panelDibujo.add(registroPasajero,0);
        registroPasajero.setLocation(panelDibujo.getUbicacion());
        registroPasajero.setResizable(false);
        registroPasajero.setVisible(true);
        btnPasajero.setVisible(false);
    }//GEN-LAST:event_btnPasajeroActionPerformed

    private void btnBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletosActionPerformed
        // TODO add your handling code here:
        try {
        comprarBoleto= new ComprarBoleto(this);
        panelDibujo.add(comprarBoleto,0);
        comprarBoleto.setLocation(panelDibujo.getUbicacion());
        //comprarBoleto.setLocation(243,0);
        comprarBoleto.setResizable(false);
        comprarBoleto.setVisible(true);
        btnBoletos.setVisible(false);    
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "No existe Aviones disponibles");
        }
        
    }//GEN-LAST:event_btnBoletosActionPerformed

    private void btnAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvionActionPerformed
        // TODO add your handling code here:
        registroAvion= new RegistroAvion(this);
        panelDibujo.add(registroAvion,0);
        registroAvion.setLocation(panelDibujo.getUbicacion());
        //registroAvion.setLocation(488,0);
        registroAvion.setResizable(false);
        registroAvion.setVisible(true);
        btnAvion.setVisible(false);
    }//GEN-LAST:event_btnAvionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        panelDibujo.remove(this);
        if(registroPasajero!=null){
            registroPasajero.hide();    panelDibujo.remove(registroPasajero);}
        if(comprarBoleto!=null){
            comprarBoleto.hide();       panelDibujo.remove(comprarBoleto);}
        if(registroAvion!=null){
            registroAvion.hide();       panelDibujo.remove(registroAvion);}
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setVisiblePasajero(){btnPasajero.setVisible(true);}
    public void setVisibleAvion(){btnAvion.setVisible(true);}
    public void setVisibleBoleto(){btnBoletos.setVisible(true);}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvion;
    private javax.swing.JButton btnBoletos;
    private javax.swing.JButton btnPasajero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
