/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Pasajero;

/**
 *
 * @author Ariel
 */
public class TablaPersonas extends javax.swing.JFrame {

    /**
     * Creates new form TablaPersonas
     */
    DefaultTableModel modelo;
    ArrayList<Pasajero> pasajeros;
    ArrayList<Pasajero> pasajerosConBoleto;
    public TablaPersonas(ArrayList<Pasajero> pasajeros,ArrayList<Pasajero> pasajerosConBoleto ) {
        this.pasajeros=pasajeros;
        this.pasajerosConBoleto=pasajerosConBoleto;
        initComponents();
        String cabecera[]={"Nombre", "CI", "Edad", "Genero", "Ubicacion"};
        String datos[][]={};
        modelo = new DefaultTableModel(datos, cabecera);
        table.setModel(modelo);
        
        int anchos [] = {160,100,100,100,100};
        for(int i=0; i<5; i++){
        	table.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        for(int i=0;i<pasajeros.size();i++){
            modelo.addRow(pasajeros.get(i).getForTable());
        }
        for(int i=0;i<pasajerosConBoleto.size();i++){
            modelo.addRow(pasajerosConBoleto.get(i).getForTable());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Personas registradas");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "CI", "Edad", "Genero", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
