/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Aeropuerto;

/**
 *
 * @author Ariel
 */
public class TablaAviones extends javax.swing.JFrame {

    /**
     * Creates new form TablaAviones
     */
    DefaultTableModel modelo;
    ArrayList<Aeropuerto> aeropuertos;
    public TablaAviones(ArrayList<Aeropuerto> aeropuertos) {
        
        this.aeropuertos=aeropuertos;
        initComponents();
        String cabecera[]={"Ubicacion","Modelo", "Placa", "Nombre", "Capacidad", "Ocupados"};
        String datos[][]={};
        modelo = new DefaultTableModel(datos, cabecera);
        table.setModel(modelo);
        int anchos [] = {160,100,100,100,100,100};
        for(int i=0; i<6; i++){
        	table.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        for(int i=0;i<aeropuertos.size();i++){
            for(int j=0;j<aeropuertos.get(i).getAviones().size();j++){
                modelo.addRow(aeropuertos.get(i).getAviones().get(j).getForTable(aeropuertos.get(i).getNombre()));
            }
        }
    }
    public String sacarModelo(int n){
        String res="";
        if(n==0)res="Boeng";
        else if(n==1)res="Grande";
        else if(n==2)res="Pequeño";
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Aviones registrados");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ubicacion", "Modelo", "Placa", "Nombre", "Capacidad", "Ocupados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
